### ISSUE TITLE
handling datetimes (possibly only in sqlite)

### ISSUE THREAD

**Issue by HoneyryderChuck** [janko/sequel-activerecord_connection#1]
Coming from https://groups.google.com/forum/#!topic/sequel-talk/r-HFhY041Vc%5B1-25%5D .

Sequel and ActiveRecord store datetimes in different formats (in sqlite, at least): sequel defaults to localtime, activerecord defaults to utc. This means that, whenever sequel grabs rows with datetimes using the activerecord connection, it gets datetimes in utc.

That in itself is not a problem, however the main problem I'm having is in date arithmetic, as `Sequel::CURRENT_TIMESTAMP` will be translated to `datetime(CURRENT_TIMESTAMP, 'localtime')`.

Some magic would therefore have to be done to just use `CURRENNT_TIMESTAMP` for the UTC case (or `datetime(CURRENT_TIMESTAMP, 'utc')`). I'm not sure if rails keeps this in a config variable or whether it defaults all the time to UTC, but some injection at the adapter level (at least for sqlite) needs to be performed in order for this to be compliant.

**Comment by janko** [comment]
Interesting, thank you for the report. Note that the extension inherits the timezone from Active Record: https://github.com/janko/sequel-activerecord_connection/blob/332183bfafbd758cde29bb24e98a396e33b98994/lib/sequel/extensions/activerecord_connection.rb#L7

However, that might not be correct level for `CURRENT_TIMESTAMP`, because in addition to `Sequel.database_timezone` (which is what gets assigned to `Sequel::Database#timezone`), there is also `Sequel.application_timezone` and `Sequel.typecast_timezone`. I'm wondering whether Sequel uses the latter for `CURRENT_TIMESTAMP`.

After further inspection, the `CURRENT_TIMESTAMP` conversion might be adapter-specific, for [SQLite at least](https://github.com/jeremyevans/sequel/blob/52a4d79ad5089b09fe6b27f3b8edeb657e8c3090/lib/sequel/adapters/shared/sqlite.rb#L547).

Jeremy's comment on the google group about overriding `#constant_sql_append` seems to be a good approach, but I still want to check what Active Record is doing.

**Comment by janko** [comment]
I realized I'm not really clear in the difference between vanilla Sequel behaviour and Sequel behaviour with ActiveRecord connection. How this gem works is that it generates the SQL string with Sequel and then gives it to Active Record to execute. So, I don't understand why do date arithmetics work with vanilla Sequel and don't when Active Record connection is used, if the end SQL query should be the same 🤔

**Comment by HoneyryderChuck** [comment]
Actually, I'm not sure whether the fix should be committed here or in `sequel` itself. However, let me propose this based on your comments:

You say that this gem sets the timezone of activerecord this way:

```ruby
db.timezone = ActiveRecord::Base.default_timezone
```

So, if I understand correctly, this attribution should have the "side-effect" of injecting a different `CURRENT_TIMESTAMP` logic, when the default timezone is UTC. Or actually, since `default_timezone` can only be `:utc` or `:local` apparently, maybe take that as an argument, and use it with the sequel `extends_dataset` plugin to "parametrize" `CURRENT_TIMESTAMP`, so it can become `datetime(CURRENT_TIMESTAMP, 'utc')` or `datetime(CURRENT_TIMESTAMP, 'localtime')`.

Does this make sense?

**Comment by janko** [comment]
Yeah, this would probably make sense for me, though I'm not sure if that would handle the situation that SQLite doesn't return the timezone in some cases, if I understood Jeremy correctly. Let's wait for his solution.

If I understand correctly, this is only problematic due to Active Record's UTC timezone. If Sequel is used with UTC timezone as well, the problem would be the same, correct?

**Comment by HoneyryderChuck** [comment]
> If I understand correctly, this is only problematic due to Active Record's UTC timezone. If Sequel is used with UTC timezone as well, the problem would be the same, correct?

I assume it does. I'm inserting the rows using sequel, so I guess it would.
