### ISSUE TITLE
Rails sequel initializer prevents rake from creating DB

### ISSUE THREAD

**Issue by lifelenz** [janko/sequel-activerecord_connection#24]
Hi, I have a config/initializers/sequel.rb set up as described in the readme, however when I then try to create a database with `rake db:create` I get a PG::ConnectionBad error because the database does not exist. It seems as soon as the initializer is run it tries to hit the database, prior to the rake task creating it.

It does work if I comment out the line `DB.extension(:sql_log_normalizer)` or guard it with:
`if (ActiveRecord::Base.connection rescue nil)`

**Comment by janko** [comment]
Interesting, it seems that the `sql_log_normalizer` extension is checking out a connection as soon as it's loaded. I will check with Jeremy if this can be avoided.

**Comment by janko** [comment]
I opened a discussion in https://github.com/jeremyevans/sequel/discussions/1995, but Jeremy would prefer to keep `sql_log_normalizer` connecting to the database when it's loaded, because it keeps the implementation simpler.

So, your workaround seems like the correct solution when configuring Sequel in an initializer. I will probably start recommending a more explicit version in the docs:

```rb
DB = Sequel.postgres(extensions: :activerecord_connection)
begin
  DB.extension :sql_log_normalizer
rescue ActiveRecord::NoDatabaseError
end
```
